name: Scrape latest data

on:
  workflow_dispatch:
  schedule:
    - cron:  '10 1 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest

    steps:
    - name: Check out this repo
      uses: actions/checkout@v6

    - name: Enable Corepack (Yarn)
      run: |-
        npm install -g corepack
        corepack enable

    - name: Setup node
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'yarn'
        cache-dependency-path: yarn.lock

    - name: Install dependencies
      run: |-
        yarn install --immutable

    - name: Run
      run: |-
        yarn start
        yarn tocsv

    - name: 'Upload Training Artifact'
      uses: actions/upload-artifact@v7
      with:
        name: training-json
        path: nypd-profiles-*-training-*.json
        retention-days: 2

    - name: 'Upload CSV Artifact'
      uses: actions/upload-artifact@v7
      with:
        name: nypd-profiles-csv
        path: |
          officers.csv
          discipline.csv
          ranks.csv
          documents.csv
          awards.csv
          training.csv
        retention-days: 2

    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A nypd-profiles-[A-Z].json trial-decisions.json
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
